### ISSUE TITLE
New Membership Emails not sending

### ISSUE THREAD

**Issue by susancevans** [nadineproject/nadine#313]
When we add a new member (today we added Saul and Mike K), there should be an email sent both to the member and to the Team alerting us of the new membership. I manually sent Saul and Mike's so they'd be prompted to log into Nadine. 

This should happen automatically, and currently does not.

**Comment by mimorita** [comment]
Additionally, at /staff/members/detail/[USER] in the "EMAIL" tab, I cannot manually send the new_membership email.

**Comment by jsayles** [comment]
This is fixed and deployed live

**Comment by mimorita** [comment]
This still does not work. New Advocate member M.F. this morning. Team email not sent, email to member not sent, cannot manually force email to send from profile.

**Comment by jsayles** [comment]
This is fixed and deployed.  Sorry I missed a step in fixing it before but we are all good now.
